### ISSUE TITLE
Portrait pictures not working

### ISSUE THREAD

**Issue by mkiisoft** [L4Digital/coreml-face-detection-sample#1]
Hello, Adam! Great example!

I did some small testing and works perfect If I took the photo horizontal but If I took a portrait photo (selfie) it doesn't get my face... the exact same face position it's getting the rect draw correctly horizontally but not portrait.

request.results is Optional([]) and horizontal picture: Optional([<VNFaceObservation: 0x1c0191780> 02F6DD29-97A6-4E52-BF72-D9D9C69481B1 1 [0.398166 0.300214 0.236094 0.419723] ID=0])

Do you were where the issue could be?

**Comment by mkiisoft** [comment]
Never mind... this snippet fix the issue:

```
if originalImage.imageOrientation != .up {
            UIGraphicsBeginImageContextWithOptions(originalImage.size, false, originalImage.scale)
            originalImage.draw(in: CGRect(origin: CGPoint(x: 0, y: 0), size: originalImage.size))
            originalImage = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
        }
```

**Comment by raid5** [comment]
Awesome, thanks for looking into this. Did you want to submit a PR to fix this up? If not I can make the adjustment.
